test: &default

  # Credentials for REST APIs
  client_id: Aaqr_6GNa9S0wNVzQJbCS7vnVoEwP5Dvt8h3S8HGeocy0pfnS_regyDYxEaGS1jOs5jRWE0hUagu9xzB
  client_secret: EFnJb1GQUFfhCpF7V27IWZeDRRqvnjssta737gMQyiD6U-nDyTXrFCj6r7RmkHcUpoG2ckZ3h7EVmfjK

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: gonzalo.grandon.s_api1.gmail.com
  password: V3PCNA57ZYKENCWQ
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31ABFrrQKSkVj6u7wmwpWOnbRPsj4V
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: gonzalo.grandon.s@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
